name: code_viwer
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  nyxx: ^3.2.7
  http: ^0.13.4

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
